name: pipeline-test-board

on:
  push:
    branches: 
      - '*'

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: prynceseitenfus/stm32cubeide:1.18.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show working directory and files
        run: |
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          pwd
          ls -l

      - name: Run build.sh
        working-directory: ${{ github.workspace }}
        run: | 
          chmod +x build.sh
          ./build.sh
