name: pipeline-test-board

on:
  push:
    branches: 
      - '*'

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: prynceseitenfus/stm32cubeide:1.18.1

    steps:
      - name: Show working directory and files
        working-directory: ../  
        run: |
            echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
            pwd
            ls -l        

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run build.sh
        working-directory: ../
        run: | 
          chmod +x ./test-board/build.sh
          ./test-board/build.sh
